inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Metrics/BlockLength:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal


Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
